version: '3.7'

services:
  se-db:
    image: postgres:12.2-alpine
    ports:
      - "5488:5432"
    volumes:
      - postgres-data2:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=db
      - POSTGRES_PASSWORD=db
      - POSTGRES_DB=db
    networks:
      - core

volumes:
  postgres-data2:

networks:
  core:
